name: Build, Test, Scan, and Push to GHCR

on:
  push:
    branches: [ master ]

jobs:
  build-test-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadless

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: dist/test-results

      - name: Build Angular App
        run: npm run build --prod

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/assetflow-web:${{ github.sha }} .

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker Image as Latest
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/assetflow-web:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/assetflow-web:latest

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/assetflow-web:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/assetflow-web:latest

      - name: Scan Docker Image with Grype
        uses: anchore/scan-action@v3
        with:
          image: "ghcr.io/${{ github.repository_owner }}/assetflow-web:${{ github.sha }}"
          fail-build: false
          severity-cutoff: high

      - name: Upload Scan Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: grype-results-image
          path: grype-report.json
